// ===========================================================================
//  NAVEGANDO SISTEMAS: ÚLTIMO ROUND — Banco de preguntas
//  Procesos, Instituciones y Política Comparada (Caps. I–XIV)
//  Preguntas generales sobre el aporte de cada autor · máx. 2 por autor.
//  Alternativas redactadas con longitud pareja (la correcta no destaca).
//  { cap, correct(0-3), q, options[4], pista }
// ===========================================================================
window.PREGUNTAS = [
  // ---- Cap. I ----
  { cap: "I", correct: 0,
    q: "Para Sartori, al pasar de la polis griega al imperio romano, la política…",
    options: ["pierde su horizontalidad entre iguales", "amplía la deliberación entre iguales", "se separa de toda autoridad central", "abandona su carácter conflictivo"],
    pista: "Sartori contrasta la política horizontal de la polis con la verticalidad del orden imperial." },
  { cap: "I", correct: 2,
    q: "Sartori advierte que un concepto de política demasiado amplio…",
    options: ["refuerza el análisis comparado", "consolida la democracia liberal", "pierde toda utilidad analítica", "elimina el papel del conflicto"],
    pista: "Si todo es político, la categoría deja de servir para distinguir y analizar." },
  { cap: "I", correct: 1,
    q: "Para Warren, ¿qué elemento es constitutivo de lo político?",
    options: ["el consenso entre actores", "el conflicto entre actores", "la burocracia del Estado", "la eficiencia del mercado"],
    pista: "Warren sostiene que sin disputa no hay nada que negociar: ese es el núcleo de lo político." },
  { cap: "I", correct: 0,
    q: "Warren critica las concepciones centradas en el Estado porque…",
    options: ["ignoran fenómenos políticos emergentes", "exageran el peso del conflicto social", "reducen la política a la economía", "abstraen demasiado las instituciones"],
    pista: "Warren mira los movimientos cívicos, culturales y éticos que el enfoque estatista no logra ver." },
  // ---- Cap. II ----
  { cap: "II", correct: 1,
    q: "El aporte central de Gerring al análisis político es…",
    options: ["clasificar los sistemas electorales", "fijar criterios para buenos conceptos", "medir el desarrollo económico", "diseñar encuestas representativas"],
    pista: "Gerring se ocupa de cómo se forma un concepto riguroso y qué requisitos debe cumplir." },
  { cap: "II", correct: 2,
    q: "Para Gerring, formar un buen concepto implica…",
    options: ["copiar una definición previa", "usar solo datos cuantitativos", "equilibrar criterios en tensión", "renunciar a toda definición"],
    pista: "Ningún concepto cumple todos los criterios a la vez: conceptualizar es negociar entre ellos." },
  // ---- Cap. III ----
  { cap: "III", correct: 3,
    q: "El criterio que Popper propone para distinguir la ciencia es la…",
    options: ["verificación empírica", "inducción sistemática", "intuición razonada", "falsación de hipótesis"],
    pista: "Para Popper, lo que distingue a la ciencia no es confirmar, sino poder refutar." },
  { cap: "III", correct: 2,
    q: "Según Popper, una teoría científica debe ser…",
    options: ["imposible de refutar", "aceptada por consenso", "susceptible de refutación", "expresada en lenguaje formal"],
    pista: "Una teoría que no puede ser puesta a prueba ni desmentida no es, para Popper, científica." },
  // ---- Cap. IV ----
  { cap: "IV", correct: 0,
    q: "El aporte de Lijphart al método comparado es distinguir entre…",
    options: ["sistemas de máxima similitud y diferencia", "regímenes de izquierda y de derecha", "economías ricas y economías pobres", "democracias del norte y del sur"],
    pista: "Lijphart sistematiza las dos formas básicas de comparar: casos parecidos (DSMS) o muy distintos (DSMD)." },
  { cap: "IV", correct: 1,
    q: "Para Lijphart, el método comparado sirve sobre todo para…",
    options: ["pronosticar procesos electorales", "inferir causas con pocos casos", "estimar el crecimiento económico", "redactar reformas constitucionales"],
    pista: "Es la herramienta para inferir causas cuando hay muchas variables y pocos casos." },
  // ---- Cap. V ----
  { cap: "V", correct: 2,
    q: "Hobbes describe la vida en el estado de naturaleza como…",
    options: ["próspera, libre y pacífica", "ordenada, estable y jerárquica", "solitaria, pobre, brutal y corta", "comunitaria, solidaria y segura"],
    pista: "Recuerden la sombría cita de Hobbes sobre la vida sin Estado: cuatro adjetivos." },
  { cap: "V", correct: 3,
    q: "La solución de Hobbes al estado de naturaleza es…",
    options: ["la democracia directa", "el libre mercado", "la asamblea popular", "el contrato social"],
    pista: "Para Hobbes, la salida del caos es un pacto: ceder poder a un soberano a cambio de orden." },
  { cap: "V", correct: 2,
    q: "La idea central de Tilly sobre el Estado moderno es que…",
    options: ["el comercio fundó al Estado", "la cultura sostiene al Estado", "la guerra y el Estado se hacen mutuamente", "la religión legitima al Estado"],
    pista: "Es un quiasmo: el conflicto bélico y el Estado se hacen mutuamente." },
  { cap: "V", correct: 1,
    q: "Para Tilly, el motor de la formación del Estado europeo fue…",
    options: ["la expansión religiosa", "la competencia militar", "el comercio marítimo", "la difusión cultural"],
    pista: "Lo que forzó la construcción del Estado fue la presión de competir y sobrevivir militarmente." },
  // ---- Cap. VI ----
  { cap: "VI", correct: 1,
    q: "Moore explica las rutas hacia la modernidad política a partir de…",
    options: ["la geografía y el territorio", "las alianzas entre clases sociales", "la religión predominante", "el tamaño de la población"],
    pista: "Moore parte de la economía agraria: tres clases cuyas alianzas definen el destino político." },
  { cap: "VI", correct: 0,
    q: "La ruta de 'revolución desde arriba' de Moore desemboca en…",
    options: ["un régimen fascista", "una democracia liberal", "un Estado comunista", "una sociedad anárquica"],
    pista: "Con élites terratenientes fuertes y burguesía débil, el camino lleva a un régimen de derecha radical." },
  { cap: "VI", correct: 3,
    q: "Para Acemoglu y Robinson, la clave para prosperar o no está en…",
    options: ["el clima del territorio", "la dotación de recursos", "la composición étnica", "el tipo de instituciones"],
    pista: "Su tesis distingue instituciones inclusivas frente a extractivas como causa del desarrollo." },
  // ---- Cap. VII ----
  { cap: "VII", correct: 2,
    q: "Mahoney distingue dos modelos de colonialismo según su economía política:",
    options: ["feudal y moderno", "agrario e industrial", "mercantilista y liberal", "centralista y federal"],
    pista: "Mahoney contrasta el modelo colonial temprano y restrictivo con el posterior, más abierto al mercado." },
  { cap: "VII", correct: 3,
    q: "Mahoney sostiene que los legados coloniales producen trayectorias…",
    options: ["idénticas entre regiones", "irrelevantes con el tiempo", "exclusivamente económicas", "duraderas y divergentes"],
    pista: "Las instituciones implantadas en la colonia condicionan el desarrollo por siglos (path dependence)." },
  { cap: "VII", correct: 3,
    q: "El concepto central del modelo de Kuran es la…",
    options: ["elección estratégica", "ventana de oportunidad", "espiral del silencio", "falsificación de preferencias"],
    pista: "Trata sobre por qué la gente oculta lo que realmente piensa bajo represión." },
  { cap: "VII", correct: 1,
    q: "El modelo de Kuran explica por qué las revoluciones…",
    options: ["jamás llegan a ocurrir", "estallan de forma imprevisible", "fracasan casi siempre", "resultan siempre violentas"],
    pista: "El descontento oculto se revela en cascada: parece surgir 'de la nada'." },
  // ---- Cap. VIII ----
  { cap: "VIII", correct: 2,
    q: "El concepto central de Putnam es el…",
    options: ["capital humano", "capital simbólico", "capital social", "capital político"],
    pista: "Habla de redes, confianza y reciprocidad que facilitan la cooperación." },
  { cap: "VIII", correct: 0,
    q: "Putnam atribuye el mejor desempeño institucional de una región a…",
    options: ["sus tradiciones cívicas históricas", "su mayor desarrollo económico", "sus condiciones geográficas", "su mayor tamaño poblacional"],
    pista: "Descarta la riqueza y apunta a algo cívico que viene arraigado desde el medioevo." },
  { cap: "VIII", correct: 1,
    q: "Inglehart asocia el desarrollo con el giro hacia valores…",
    options: ["tradicionales", "postmaterialistas", "estrictamente religiosos", "marcadamente autoritarios"],
    pista: "Describe el giro hacia la autoexpresión propio de sociedades que ya superaron la escasez." },
  { cap: "VIII", correct: 0,
    q: "Para Inglehart, el cambio cultural ocurre principalmente…",
    options: ["entre generaciones, de forma lenta", "de un día para otro, por crisis", "solo mediante decretos del Estado", "al margen del desarrollo económico"],
    pista: "El cambio de valores es intergeneracional: las nuevas cohortes traen prioridades distintas." },
  // ---- Cap. IX ----
  { cap: "IX", correct: 3,
    q: "El concepto de Dahl para la democracia realmente existente es…",
    options: ["la república", "la tecnocracia", "la democracia delegativa", "la poliarquía"],
    pista: "Es la democracia 'realmente observable', distinta del ideal inalcanzable." },
  { cap: "IX", correct: 0,
    q: "Las dos dimensiones de la poliarquía de Dahl son…",
    options: ["inclusión y contestación", "libertad e igualdad jurídica", "orden público y progreso", "Estado fuerte y mercado libre"],
    pista: "Una mide cuántos participan; la otra, cuánto se puede competir y disentir." },
  { cap: "IX", correct: 2,
    q: "Para Christiano, el valor que fundamenta la democracia es…",
    options: ["la eficiencia del gobierno", "el respeto a la tradición", "la igualdad de las personas", "la prosperidad económica"],
    pista: "Christiano funda la autoridad democrática en el trato igualitario de los intereses de todos." },
  // ---- Cap. X ----
  { cap: "X", correct: 3,
    q: "Linz advierte que el presidencialismo genera una legitimidad…",
    options: ["popular", "única", "delegada", "dual"],
    pista: "Dos poderes electos —presidente y congreso— pueden reclamar a la vez representar al pueblo." },
  { cap: "X", correct: 1,
    q: "Cheibub sostiene que la inestabilidad presidencial se explica por…",
    options: ["el diseño de la constitución", "el legado militar previo", "el sistema de partidos", "la cultura política local"],
    pista: "Cheibub dice que no es el diseño, sino de dónde vienen esos países: su pasado castrense." },
  // ---- Cap. XI ----
  { cap: "XI", correct: 1,
    q: "La distinción fundamental de Linz entre regímenes no democráticos es…",
    options: ["monarquía frente a república", "totalitarismo frente a autoritarismo", "régimen civil frente a militar", "régimen de izquierda frente a derecha"],
    pista: "Separa el régimen de ideología total del de mentalidad difusa y pluralismo limitado." },
  { cap: "XI", correct: 0,
    q: "A diferencia del autoritarismo, el totalitarismo se caracteriza por…",
    options: ["movilizar masas con partido único", "tolerar un pluralismo limitado", "despolitizar a la población", "ejercer represión selectiva"],
    pista: "Lo propio del régimen total es un partido único que moviliza activamente, no que desmoviliza." },
  { cap: "XI", correct: 3,
    q: "El 'autoritarismo competitivo' de Levitsky y Way describe regímenes que…",
    options: ["prohíben cualquier elección", "alcanzan plena democracia", "carecen de todo gobierno", "compiten en cancha dispareja"],
    pista: "Hay competencia electoral genuina, pero el juego está inclinado a favor del oficialismo." },
  // ---- Cap. XII ----
  { cap: "XII", correct: 2,
    q: "Para Ware, los partidos políticos tienen una naturaleza…",
    options: ["puramente electoral", "puramente ideológica", "dual y representativa", "secundaria y marginal"],
    pista: "Ware subraya la doble cara del partido: busca cargos y a la vez representa demandas sociales." },
  { cap: "XII", correct: 1,
    q: "La 'tesis del congelamiento' de Lipset y Rokkan dice que los partidos…",
    options: ["cambian en cada elección", "reflejan clivajes históricos", "surgen de modo azaroso", "carecen de raíces sociales"],
    pista: "Los partidos cristalizan divisiones sociales antiguas y quedan 'congelados' por décadas." },
  // ---- Cap. XIII ----
  { cap: "XIII", correct: 0,
    q: "La 'ley de Duverger' vincula el sistema de mayoría simple con…",
    options: ["el bipartidismo", "el multipartidismo", "el partido hegemónico", "el abstencionismo"],
    pista: "El sistema de mayoría en distritos uninominales tiende a dejar dos grandes partidos." },
  { cap: "XIII", correct: 3,
    q: "Para Duverger, el sistema electoral influye sobre todo en…",
    options: ["el desarrollo económico", "la composición geográfica", "la afiliación religiosa", "el número de partidos"],
    pista: "Las reglas electorales moldean cuántos partidos llegan a ser competitivos." },
  { cap: "XIII", correct: 2,
    q: "Para Boix, los sistemas electorales se adoptan según…",
    options: ["la herencia histórica", "el azar de la coyuntura", "el cálculo de las élites", "la presión internacional"],
    pista: "Boix explica la elección de las reglas por el interés de los partidos que las diseñan." },
  // ---- Cap. XIV ----
  { cap: "XIV", correct: 0,
    q: "El modelo de Zaller explica la formación de…",
    options: ["la opinión pública", "los partidos políticos", "las coaliciones de gobierno", "los clivajes sociales"],
    pista: "Su modelo (recibir-aceptar-muestrear) describe cómo se forma lo que la gente opina." },
  { cap: "XIV", correct: 1,
    q: "Para Zaller, la opinión que alguien expresa depende sobre todo de…",
    options: ["su nivel de ingreso actual", "las ideas que tiene a mano", "su lugar de nacimiento", "su edad en ese momento"],
    pista: "La respuesta surge de las ideas accesibles al momento de responder, no de una opinión fija." }
];
