// ===========================================================================
//  NAVEGANDO SISTEMAS: ÚLTIMO ROUND — Banco de preguntas
//  Procesos, Instituciones y Política Comparada (Caps. I–XIV)
//  Preguntas generales sobre el aporte de cada autor · máx. 2 por autor.
//  { cap, correct(0-3), q, options[4], pista }
// ===========================================================================
window.PREGUNTAS = [
  // ---- Cap. I ----
  { cap: "I", correct: 3,
    q: "Para Sartori, ¿cómo cambia la política al pasar de la polis griega al imperio romano?",
    options: ["desaparece por completo", "se separa de la religión", "se vuelve más participativa", "pierde su horizontalidad entre iguales"],
    pista: "Sartori contrasta la política horizontal de la polis con la verticalidad del orden imperial." },
  { cap: "I", correct: 0,
    q: "Sartori advierte que un concepto de política demasiado amplio…",
    options: ["pierde utilidad analítica", "mejora el análisis", "elimina el conflicto", "amplía la democracia"],
    pista: "Si todo es político, la categoría deja de servir para distinguir y analizar." },
  { cap: "I", correct: 3,
    q: "Para Warren, ¿qué elemento es constitutivo de lo político?",
    options: ["el mercado", "la burocracia", "el consenso", "el conflicto"],
    pista: "Warren sostiene que sin disputa no hay nada que negociar: ese es el núcleo de lo político." },
  { cap: "I", correct: 0,
    q: "Warren critica las concepciones centradas en el Estado porque…",
    options: ["no captan los fenómenos políticos emergentes", "son demasiado abstractas", "exageran el conflicto", "ignoran la economía"],
    pista: "Warren mira los movimientos cívicos, culturales y éticos que el enfoque estatista no logra ver." },
  // ---- Cap. II ----
  { cap: "II", correct: 2,
    q: "¿Cuál es el aporte central de Gerring al análisis político?",
    options: ["clasificar sistemas electorales", "medir el PIB de las democracias", "proponer criterios para construir buenos conceptos", "diseñar encuestas"],
    pista: "Gerring se ocupa de cómo se forma un concepto riguroso y qué requisitos debe cumplir." },
  { cap: "II", correct: 3,
    q: "Para Gerring, formar un buen concepto implica…",
    options: ["evitar toda definición", "copiar definiciones previas", "usar siempre datos cuantitativos", "equilibrar criterios que rara vez se cumplen todos a la vez"],
    pista: "Ningún concepto cumple todos los criterios a la vez: conceptualizar es negociar entre ellos." },
  // ---- Cap. III ----
  { cap: "III", correct: 3,
    q: "El criterio que Popper propone para distinguir la ciencia es la…",
    options: ["verificación", "inducción", "intuición", "falsación"],
    pista: "Para Popper, lo que distingue a la ciencia no es confirmar, sino poder refutar." },
  { cap: "III", correct: 1,
    q: "Según Popper, una teoría científica debe ser…",
    options: ["matemática", "refutable", "consensuada", "irrefutable"],
    pista: "Una teoría que no puede ser puesta a prueba ni desmentida no es, para Popper, científica." },
  // ---- Cap. IV ----
  { cap: "IV", correct: 1,
    q: "El aporte de Lijphart al método comparado es distinguir entre…",
    options: ["ricos y pobres", "sistemas de máxima similitud y de máxima diferencia", "izquierda y derecha", "norte y sur"],
    pista: "Lijphart sistematiza las dos formas básicas de comparar: casos parecidos (DSMS) o muy distintos (DSMD)." },
  { cap: "IV", correct: 2,
    q: "Para Lijphart, el método comparado sirve principalmente para…",
    options: ["medir la economía", "redactar constituciones", "establecer relaciones causales con pocos casos", "predecir elecciones"],
    pista: "Es la herramienta para inferir causas cuando hay muchas variables y pocos casos." },
  // ---- Cap. V ----
  { cap: "V", correct: 0,
    q: "Hobbes describe la vida en el estado de naturaleza como…",
    options: ["solitaria, pobre, brutal y corta", "comunitaria", "próspera y libre", "ordenada y jerárquica"],
    pista: "Recuerden la sombría cita de Hobbes sobre la vida sin Estado: cuatro adjetivos." },
  { cap: "V", correct: 2,
    q: "La solución de Hobbes al estado de naturaleza es…",
    options: ["la democracia directa", "el libre mercado", "el contrato social", "la asamblea popular"],
    pista: "Para Hobbes, la salida del caos es un pacto: ceder poder a un soberano a cambio de orden." },
  { cap: "V", correct: 1,
    q: "La frase célebre de Tilly sobre el Estado moderno es…",
    options: ["el Estado somos todos", "la guerra hace al Estado y el Estado hace la guerra", "el fin justifica los medios", "todo poder corrompe"],
    pista: "Es un quiasmo: el conflicto bélico y el Estado se hacen mutuamente." },
  { cap: "V", correct: 1,
    q: "Para Tilly, el motor de la formación del Estado europeo fue…",
    options: ["el comercio marítimo", "la competencia militar", "la religión", "la imprenta"],
    pista: "Lo que forzó la construcción del Estado fue la presión de competir y sobrevivir militarmente." },
  // ---- Cap. VI ----
  { cap: "VI", correct: 1,
    q: "Moore explica las rutas hacia la modernidad política a partir de…",
    options: ["la religión dominante", "las relaciones entre aristocracia, burguesía y campesinado", "el tamaño del país", "la geografía"],
    pista: "Moore parte de la economía agraria: tres clases cuyas alianzas definen el destino político." },
  { cap: "VI", correct: 3,
    q: "La ruta de 'revolución desde arriba' de Moore desemboca en…",
    options: ["el comunismo", "la democracia", "la anarquía", "el fascismo"],
    pista: "Con élites terratenientes fuertes y burguesía débil, el camino lleva a un régimen de derecha radical." },
  { cap: "VI", correct: 1,
    q: "Para Acemoglu y Robinson, la diferencia clave entre prosperar o no está en…",
    options: ["la raza", "el tipo de instituciones", "los recursos naturales", "el clima"],
    pista: "Su tesis distingue instituciones inclusivas frente a extractivas como causa del desarrollo." },
  // ---- Cap. VII ----
  { cap: "VII", correct: 2,
    q: "Mahoney distingue dos modelos de colonialismo según su economía política:",
    options: ["feudal y moderno", "centralista y federal", "mercantilista y liberal", "agrario e industrial"],
    pista: "Mahoney contrasta el modelo colonial temprano y restrictivo con el posterior, más abierto al mercado." },
  { cap: "VII", correct: 2,
    q: "Mahoney sostiene que los legados coloniales producen trayectorias de desarrollo…",
    options: ["puramente económicas", "irrelevantes a largo plazo", "duraderas y divergentes", "idénticas en todos los casos"],
    pista: "Las instituciones implantadas en la colonia condicionan el desarrollo por siglos (path dependence)." },
  { cap: "VII", correct: 2,
    q: "El concepto central del modelo de Kuran es la…",
    options: ["espiral del silencio", "elección racional", "falsificación de preferencias", "ventana de oportunidad"],
    pista: "Trata sobre por qué la gente oculta lo que realmente piensa bajo represión." },
  { cap: "VII", correct: 2,
    q: "El modelo de Kuran explica por qué las revoluciones…",
    options: ["siempre fracasan", "nunca ocurren", "estallan de forma súbita e imprevisible", "son siempre violentas"],
    pista: "El descontento oculto se revela en cascada: parece surgir 'de la nada'." },
  // ---- Cap. VIII ----
  { cap: "VIII", correct: 0,
    q: "El concepto central de Putnam es el…",
    options: ["capital social", "capital humano", "capital político", "capital simbólico"],
    pista: "Habla de redes, confianza y reciprocidad que facilitan la cooperación." },
  { cap: "VIII", correct: 1,
    q: "Putnam atribuye el mejor desempeño institucional de una región a…",
    options: ["su mayor riqueza", "sus tradiciones cívicas históricas", "su clima", "su tamaño"],
    pista: "Descarta la riqueza y apunta a algo cívico que viene arraigado desde el medioevo." },
  { cap: "VIII", correct: 0,
    q: "Inglehart asocia el desarrollo con el cambio hacia valores…",
    options: ["postmaterialistas", "autoritarios", "religiosos", "tradicionales"],
    pista: "Describe el giro hacia la autoexpresión propio de sociedades que ya superaron la escasez." },
  { cap: "VIII", correct: 1,
    q: "Para Inglehart, el cambio cultural se produce sobre todo…",
    options: ["solo por decreto estatal", "entre generaciones, lentamente", "de un día para otro", "sin relación con la economía"],
    pista: "El cambio de valores es intergeneracional: las nuevas cohortes traen prioridades distintas." },
  // ---- Cap. IX ----
  { cap: "IX", correct: 2,
    q: "El concepto de Dahl para la democracia realmente existente es…",
    options: ["tecnocracia", "democracia delegativa", "poliarquía", "república"],
    pista: "Es la democracia 'realmente observable', distinta del ideal inalcanzable." },
  { cap: "IX", correct: 2,
    q: "Las dos dimensiones de la poliarquía de Dahl son…",
    options: ["libertad e igualdad", "Estado y mercado", "inclusión y contestación", "orden y progreso"],
    pista: "Una mide cuántos participan; la otra, cuánto se puede competir y disentir." },
  { cap: "IX", correct: 3,
    q: "Para Christiano, el valor fundamental que justifica la democracia es…",
    options: ["la riqueza", "la tradición", "la eficiencia", "la igualdad"],
    pista: "Christiano funda la autoridad democrática en el trato igualitario de los intereses de todos." },
  // ---- Cap. X ----
  { cap: "X", correct: 0,
    q: "Linz advierte que el presidencialismo genera una 'legitimidad…'",
    options: ["dual", "popular", "delegada", "única"],
    pista: "Dos poderes electos —presidente y congreso— pueden reclamar a la vez representar al pueblo." },
  { cap: "X", correct: 2,
    q: "Cheibub sostiene que la inestabilidad de los presidencialismos se explica mejor por…",
    options: ["el sistema electoral", "el diseño institucional", "su legado autoritario-militar previo", "la cultura nacional"],
    pista: "Cheibub dice que no es el diseño, sino de dónde vienen esos países: su pasado castrense." },
  // ---- Cap. XI ----
  { cap: "XI", correct: 3,
    q: "La distinción fundamental de Linz entre regímenes no democráticos es…",
    options: ["monarquía vs. república", "civil vs. militar", "izquierda vs. derecha", "totalitarismo vs. autoritarismo"],
    pista: "Separa el régimen de ideología total del de mentalidad difusa y pluralismo limitado." },
  { cap: "XI", correct: 0,
    q: "A diferencia del autoritarismo, el totalitarismo se caracteriza por…",
    options: ["movilizar a las masas con un partido único", "usar represión selectiva", "despolitizar a la sociedad", "permitir pluralismo limitado"],
    pista: "Lo propio del régimen total es un partido único que moviliza activamente, no que desmoviliza." },
  { cap: "XI", correct: 0,
    q: "El concepto de 'autoritarismo competitivo' de Levitsky y Way describe regímenes que…",
    options: ["tienen elecciones reales pero cancha dispareja", "prohíben toda elección", "no tienen gobierno", "son plenamente democráticos"],
    pista: "Hay competencia electoral genuina, pero el juego está inclinado a favor del oficialismo." },
  // ---- Cap. XII ----
  { cap: "XII", correct: 3,
    q: "Para Ware, los partidos políticos tienen una naturaleza…",
    options: ["puramente ideológica", "irrelevante", "puramente electoral", "dual: compiten por el poder y agregan intereses"],
    pista: "Ware subraya la doble cara del partido: busca cargos y a la vez representa demandas sociales." },
  { cap: "XII", correct: 0,
    q: "La 'tesis del congelamiento' de Lipset y Rokkan sostiene que los sistemas de partidos…",
    options: ["reflejan clivajes sociales históricos", "no tienen raíces sociales", "cambian cada elección", "dependen del azar"],
    pista: "Los partidos cristalizan divisiones sociales antiguas y quedan 'congelados' por décadas." },
  // ---- Cap. XIII ----
  { cap: "XIII", correct: 1,
    q: "La 'ley de Duverger' vincula el sistema de mayoría simple con…",
    options: ["el multipartidismo", "el bipartidismo", "el partido único", "la abstención"],
    pista: "El sistema de mayoría en distritos uninominales tiende a dejar dos grandes partidos." },
  { cap: "XIII", correct: 0,
    q: "Para Duverger, el sistema electoral influye principalmente en…",
    options: ["el número de partidos", "la economía", "la religión", "la geografía"],
    pista: "Las reglas electorales moldean cuántos partidos llegan a ser competitivos." },
  { cap: "XIII", correct: 3,
    q: "Para Boix, los sistemas electorales se adoptan según…",
    options: ["la tradición histórica", "el azar", "la presión externa", "el cálculo estratégico de las élites"],
    pista: "Boix explica la elección de las reglas por el interés de los partidos que las diseñan." },
  // ---- Cap. XIV ----
  { cap: "XIV", correct: 3,
    q: "El modelo de Zaller explica la formación de…",
    options: ["las coaliciones", "los clivajes", "los partidos", "la opinión pública"],
    pista: "Su modelo (recibir-aceptar-muestrear) describe cómo se forma lo que la gente opina." },
  { cap: "XIV", correct: 1,
    q: "Para Zaller, la opinión que alguien expresa depende sobre todo de…",
    options: ["su lugar de nacimiento", "las consideraciones que tiene a mano en ese momento", "su nivel de ingreso", "su edad exacta"],
    pista: "La respuesta surge de las ideas accesibles al momento de responder, no de una opinión fija." }
];
